server:
  port: 8080

datasource:
  plataform: mysql
  url: jdbc:h2:mem:speciality_database
  username: speciality-app
  password: speciality-app!

logging:
  INFO:
    logging:
      file: /logs/application-debug.log